export const ADD_NEW_SETTLE_SHEET = 'ADD_NEW_SETTLE_SHEET';
export const GET_SETTLE_SHEETS_FROM_LOCAL_API = 'GET_SETTLE_SHEETS_FROM_LOCAL_API';
export const GET_SETTLE_SHEET_DETAILS_BY_ID = 'GET_SETTLE_SHEET_DETAILS_BY_ID';
export const UPDATE_SETTLE_SHEET_INFO = 'UPDATE_SETTLE_SHEET_INFO';
export const CLEAR_SETTLE_SHEET_DETAIL_FROM_STORE = 'CLEAR_SETTLE_SHEET_DETAIL_FROM_STORE';
export const CLEAR_SETTLE_SHEET_LIST_FROM_STORE = 'CLEAR_SETTLE_SHEET_LIST_FROM_STORE';

export const DISPLAY_SETTLE_SHEET_START_TOGGLE = 'DISPLAY_SETTLE_SHEET_START_TOGGLE';
export const HIDE_SETTLE_SHEET_START_TOGGLE = 'HIDE_SETTLE_SHEET_START_TOGGLE';
export const DISPLAY_SETTLE_SHEET_DETAILS_TOGGLE = 'DISPLAY_SETTLE_SHEET_DETAILS_TOGGLE';
export const HIDE_SETTLE_SHEET_DETAILS_TOGGLE = 'HIDE_SETTLE_SHEET_DETAILS_TOGGLE';




