export const ADD_NEW_SETTLE_SHEET = 'ADD_NEW_SETTLE_SHEET';
export const DISPLAY_SETTLE_SHEET_START_TOGGLE = 'DISPLAY_SETTLE_SHEET_START_TOGGLE';
export const HIDE_SETTLE_SHEET_START_TOGGLE = 'HIDE_SETTLE_SHEET_START_TOGGLE';